# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Minion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('minionID', models.IntegerField()),
                ('posX', models.IntegerField()),
                ('posY', models.IntegerField()),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
